### PR TITLE
Added ssh-keys

### PR DESCRIPTION
**Pull request by awlx**

### CODE REVIEW

**Review by LukeSiX — APPROVED** [review]
Passt, dann bin ich nicht mehr der einzige

**Comment by rotanid** [comment]
it's definitely no good idea to use ssh-dss keys ... they are disabled since openssh 7.0 anyway, which was released in 2015

**Comment by awlx** [comment]
Those are just old settings, we just added new ones.

**Comment by rotanid** [comment]
yes i know, but one of the newly added keys is DSS

**Pull request merged**
